# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "ogp"
primary_region = "ams"

[build]

[env]
PORT = "8080"
PUBLIC_URL = "https://ogp.fly.dev"
RUST_LOG = "info,simplecss=error"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
size = "shared-cpu-1x"
memory = "256mb"
cpus = 1

[[http_service.checks]]
interval = "30s"
timeout = "5s"
grace_period = "10s"
method = "GET"
path = "/health"
